spring.application.name=TextAnalyser-WebGate
server.port=8080
server.servlet.context-path=/webgate

logging.level.root=INFO
logging.level.com.noprobit=DEBUG

# Internet Search Configuration
webgate.search.enabled=true
webgate.search.timeout=5000

# HTTP Client Configuration
spring.http.client.connect-timeout=5000
spring.http.client.read-timeout=5000
